server:
  port: 9091

spring:
  application:
    name: 00-user_service
  main:
    banner-mode: console

  profiles:
    active: local

#Oracle configuration
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}

#jpa configuration
  jpa:
    show-sql: ${jpa.show-sql}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: ${jpa.properties.hibernate.format_sql}
  

  config.import:
  - optional:configserver:http://localhost:8080


#oracle configuration
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1521/orcl
#    username: system
#    password: manager
#    driver-class-name: oracle.jdbc.OracleDriver

#jpa configuration
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

